# Generated by Django 5.0.4 on 2024-04-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='data',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
