# Generated by Django 5.0.4 on 2024-04-20 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_links', '0002_companies_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesions',
            name='id_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redirect_links.companies'),
        ),
    ]
