# Generated by Django 5.0.4 on 2024-04-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_links', '0003_alter_sesions_id_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='sesions',
            name='user_id',
        ),
    ]
