# Generated by Django 5.0.4 on 2024-04-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_links', '0004_remove_companies_user_id_remove_sesions_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesions',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
