# Generated by Django 5.0.4 on 2024-04-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_links', '0005_alter_sesions_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesions',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
