# Generated by Django 5.0.4 on 2024-04-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirect_links', '0007_alter_companies_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesions',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
